### ISSUE TITLE
Relative pathing for rest routes

### ISSUE THREAD

**Issue by grumpy-admin99** [jpsider/RestPS#31]
It would be good to not have to provide abolute pathing for ps scripts.
I was thinking something along the lines of:
in the start-RestPSListener use the RestPSLocalRoot param
then:
function Invoke-RequestRouter{
param (...
   [Parameter(Mandatory = $false)][String]$RestPSLocalRoot = $PSScriptRoot
...)
   Set-Location $RestPSLocalRoot

this will allow relative path in the ps calls - eg: 
"RequestCommand": "./Invoke-GetRoutes.ps1"

**Comment by jpsider** [comment]
I'm not opposed to this. Have you tested it locally?

**Comment by grumpy-admin99** [comment]
yes I have - working beautifully so far.

**Comment by jpsider** [comment]
would you be willing to submit a PR for it?
