### ISSUE TITLE
can not find Invoke-AvailableRouteSet

### ISSUE THREAD

**Issue by chengerchao** [jpsider/RestPS#34]
Hi:
    I depoly RestPS as readme, but can not find Invoke-AvailableRouteSet. Could you help me resolve it.

![image](https://user-images.githubusercontent.com/21985505/71607479-de2fbe80-2bb4-11ea-8c3e-05778921f055.png)

**Comment by jpsider** [comment]
Can you tell me what version of RestPS you are using?
Run this to list all of the available modules:
Get-Module -ListAvailable

**Comment by jpsider** [comment]
Looks like I have not updated the docs in a while. It now uses a 'json' file vs. a .ps1. I have updated the readme with the correct file name:   
    $RestPSparams = @{
                RoutesFilePath = 'C:\RestPS\endpoints\RestPSRoutes.json'
                Port = '8080'
            }
    Start-RestPSListener @RestPSparams'

**Comment by chengerchao** [comment]
> Looks like I have not updated the docs in a while. It now uses a 'json' file vs. a .ps1. I have updated the readme with the correct file name:
> $RestPSparams = @{
> RoutesFilePath = 'C:\RestPS\endpoints\RestPSRoutes.json'
> Port = '8080'
> }
> Start-RestPSListener @RestPSparams'



> Looks like I have not updated the docs in a while. It now uses a 'json' file vs. a .ps1. I have updated the readme with the correct file name:
> $RestPSparams = @{
> RoutesFilePath = 'C:\RestPS\endpoints\RestPSRoutes.json'
> Port = '8080'
> }
> Start-RestPSListener @RestPSparams'

Thanks you very much, my question is resolved. please update readme, Thank you again.
