### ISSUE TITLE
Logging: request / response / error

### ISSUE THREAD

**Issue by Lichtsinnig** [jpsider/RestPS#36]
How can I configure request / response / error logging?

**Comment by jpsider** [comment]
are you using windows or linux? To be honest there are 2 other open issues for logging, because it really has not been addressed. Let me see if I can get some time to focus on a logging solution.

**Comment by Lichtsinnig** [comment]
@jpsider 
windows

**Comment by jpsider** [comment]
tracking this issue on #33
