### ISSUE TITLE
Examples AclList

### ISSUE THREAD

**Issue by Lichtsinnig** [jpsider/RestPS#37]
Write examples of using AclList. It’s not clear from the description how to configure this.

**Comment by jpsider** [comment]
Are you using windows or linux?

**Comment by Lichtsinnig** [comment]
@jpsider 
> Вы используете Windows или Linux?
windows

**Comment by jpsider** [comment]
Can you translate?
if the question is can you run this on Linux, the answer is YES!

**Comment by jpsider** [comment]
in the 'bin' directory is a function called 'Get-RestAclList'
That is where I get the data to check the user. Ideally, you would create your own logic in 'Get-RestAclList' to create your own ACL list.
Does that help?

**Comment by Lichtsinnig** [comment]
I am using windows. How do i configure acl? Write an example
