### ISSUE TITLE
Invoke-DeployRestPS -LocalDir 'C:\RestPS' issue

### ISSUE THREAD

**Issue by chengerchao** [jpsider/RestPS#43]
Hi:

  i deploy RestPS follow https://github.com/jpsider/RestPS. when i run Invoke-DeployRestPS -LocalDir 'C:\RestPS' issue . it says Parameter cannot be empty。Detail information as follows:

Invoke-DeployRestPS: 无法将参数绑定到参数“Logfile”，因为该参数为空字符串。
所在位置 C:\Program Files\WindowsPowerShell\Modules\RestPS\7.0.22\RestPS.psm1:454 字符: 9
+         Throw "Invoke-DeployRestPS: $ErrorMessage $FailedItem"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Invoke-DeployRe...e”，因为该参数为空字符串。 :String) [], RuntimeExce
ption
    + FullyQualifiedErrorId : Invoke-DeployRestPS: 无法将参数绑定到参数“Logfile”，因为该参数为空字符串。

Thanks. @jpsider @mikefrobbins

**Comment by jpsider** [comment]
You should be good now. I neglected to add some parameters last week when I added basic logging to the module. let me know i the problem persists.
