### ISSUE TITLE
Check for Administrative Permissions?

### ISSUE THREAD

**Issue by robinmalik** [jpsider/RestPS#56]
Hi,

Decided to revisit this module for some tinkering and immediately hit issues with `Invoke-DeployRestPS` re: not running as admin (though the errors were not clear). Could we not implement a simple check to see if the script is running with elevated privileges? I'm not sure if this module is cross-platform though; the check I had in mind is Windows specific.

Thoughts?

**Comment by robinmalik** [comment]
Actually, the issue I'm having doesn't even appear related to administrative permissions. Following the instructions, installing RestPS from the gallery, then launching an administrative shell, importing the module and running `Invoke-DeployRestPS` generates many Copy-Item errors. The only files that end up in C:\RestPS are:

![image](https://user-images.githubusercontent.com/8790561/117542898-6e381080-b012-11eb-9454-e701b90091a8.png)

I'll see if I can figure out what's going on with this.

**Comment by jpsider** [comment]
Just remember the Invoke-Deploy is just an example and not required. If you want to store your endpoint scripts and Json somewhere else, you can. Happy to help you along your journey.

**Comment by robinmalik** [comment]
Indeed. I've been working out of another directory but hit issues so wanted to try with a 'fresh' copy. The issue above was the fact that C:/RestPS already existed so the subfolders failed be created, which in turn caused the copy-item lines to break. I'll revert back to my original way of working and close this for now! Thanks.
