### ISSUE TITLE
Response/Return values to API call

### ISSUE THREAD

**Issue by kmschmehl** [jpsider/RestPS#62]
Hi there -

Thanks for making this module - very useful!  I am trying to make a custom failure response if my script meets a certain criteria.  Is there any support/examples for returning a non-standard failure response?

**Comment by jpsider** [comment]
what would you expect the response to look like?

**Comment by kmschmehl** [comment]
I’d like to provide a custom return from my functions with more descriptive messages.  For instance, if I run a try/catch in the catch area I’d like to be descriptive about why the API call failed (couldn’t find object, object already exists, etc) or provide the error message from the API/function that I am calling.

From what I can tell if I return a message/json, the status returned is always 0.  I’d like to return a string/json and specify the status code returned.
________________________________

**Comment by jpsider** [comment]
You should be able to achieve this by these two settings in your script:
$script:StatusCode
$script:StatusDescription
