### ISSUE TITLE
Not able to handle multiple requests (endpoints) with Weblistner

### ISSUE THREAD

**Issue by Ravicrr** [jpsider/RestPS#64]
@jpsider We have exposed few endpoints in  RestPSRoutes.json using RestPS module.
We can call only one endpoint (url) at a time. If we hit second endpoint, it waits till 1st one completes and then kicks off second request. Do we have any solution to hit multiple endpoints concurrently? Appreciate your input on this.

**Comment by jpsider** [comment]
Currently it is single threaded. I have not had a chance to look into options for multiple threads. I'm open to suggestions and contributions.

**Comment by Ravicrr** [comment]
Thanks. Let me know if you get a chance to look at any option to make it multi threaded or any suggestion on how we can implement this.

**Comment by jpsider** [comment]
duplicate of #77
