### ISSUE TITLE
I've build a container out of RestPS

### ISSUE THREAD

**Issue by NopeNix** [jpsider/RestPS#65]
Just want to give notice :-)

[https://hub.docker.com/r/nopenix/restps](https://hub.docker.com/r/nopenix/restps)

**Comment by jpsider** [comment]
Awesome! Love to see folks using my projects!
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I love when folks use my <a href="https://twitter.com/hashtag/OpenSource?src=hash&amp;ref_src=twsrc%5Etfw">#OpenSource</a> projects and then build on them! <a href="https://t.co/FVgza7218A">https://t.co/FVgza7218A</a><a href="https://twitter.com/hashtag/PowerShell?src=hash&amp;ref_src=twsrc%5Etfw">#PowerShell</a> <a href="https://twitter.com/hashtag/RestPS?src=hash&amp;ref_src=twsrc%5Etfw">#RestPS</a></p>&mdash; Justin Sider (@jpsider) <a href="https://twitter.com/jpsider/status/1488311962643619849?ref_src=twsrc%5Etfw">February 1, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by NopeNix** [comment]
Thanks for Coding! 👍
