### ISSUE TITLE
Json Truncated RestPS

### ISSUE THREAD

**Issue by VictorVanhoorenHogent** [jpsider/RestPS#76]
I'm loving the module so far, but I seem to get a truncated Json response. I assume the RestPs module uses the Convert-To-Json module at the end of the request. The problem is that this module only has a depth of 2 and I need more depth to readout the complete request. How can I achieve this functionality with RestPS?

**Comment by jpsider** [comment]
I see on line 20 of Invoke-StreamOutput
$message = $script:result | ConvertTo-Json

Are you suggesting that we add more depth here? Have you tested this? Are you interested in adding a Pull Request

**Comment by VictorVanhoorenHogent** [comment]
I think that could be a solution yes.

**Comment by jpsider** [comment]
Are you able to test this locally and make a pull request? or did you want me to handle that?

**Comment by VictorVanhoorenHogent** [comment]
I' don't really have a lot of experience with developing PowerShell modules. If you could make the level higher that would help me a lot. In the future you could maybe look at a parameter "level" that can be configured when starting the module.

**Comment by jpsider** [comment]
Do you have an idea of what the depth should be? Or what do you need it to be to support your current request?

**Comment by VictorVanhoorenHogent** [comment]
I think 10 would be a good starting point. I might look into contributing to add an extra parameter depth when you start the listener with Start-RestPSListener.

**Comment by jpsider** [comment]
ok, I will see what I can knock out of the next day or so.

**Comment by jpsider** [comment]
https://www.powershellgallery.com/packages/RestPS/7.0.54 - has been deployed with a depth of 10.
Tested locally and did not seem to impact my basic tests. 
Let me know if it resolves it for you.

**Comment by VictorVanhoorenHogent** [comment]
It work fine now, thanks again for creating this wonderful PowerShell module!
