### ISSUE TITLE
Enhance security by protecting the shutdown

### ISSUE THREAD

**Issue by chbwien** [jpsider/RestPS#78]
To my knowledge, the /endpoint/shutdown is hardcoded. How can this be changed, so a shutdown can be set to any URL AND needs a password or token? Currently, if someone knows I am running this module, s/he can call this fixed URL and shut down the REST server...

**Comment by jpsider** [comment]
Well, we could update this to be 'behind' whatever authenticate you are providing. Do you think that would be a POST or a PUT?

**Comment by jpsider** [comment]
Sounds reasonable. Want to do a PR? Or want me to make the changes?

**Comment by chbwien** [comment]
If you want me to do it, I should have this in a day or two.

**Comment by jpsider** [comment]
Yeah, go ahead and give it a shot!

**Comment by chbwien** [comment]
It was only a very small change. So it is done. See my pull request.

**Comment by jpsider** [comment]
New version deployed!
https://www.powershellgallery.com/packages/RestPS/7.0.56
