### ISSUE TITLE
Validate Client IP Code

### ISSUE THREAD

**Issue by stigjoergensen** [jpsider/RestPS#83]
Hi, 

Perhaps im blind, but im not able to find information about how to validate the clients IP address.  It is mentioned in the documentation,  but i cannot find the code on how it works... ive followed the code so far:

Start-RestPSListener, calling Invoke-ValidateIP.  this function is found in and /private, but looking at the script it does "import" /bin/get-RestIPAuth.ps1 and using an object created by this function called UserIP.  So Far so good.

But the script get-RestIPAuth.ps1 is missing 

Im not able to find it in github, and also not after i have performed Invoke-DeployRestPS

Just a side thing - the Invoke-DeployRestPS seems always want to use C:\RestPS folder and not a folder you specify - i have not digged into to this, if it was something i did.. so not too sure about it..

**Comment by jpsider** [comment]
This file is missing?

https://github.com/jpsider/RestPS/blob/master/RestPS/bin/Get-RestIPAuth.ps1

I checked the deploy function and it accepts a '$localdir' variable. 

I don't think I have tried a different directory.

**Comment by stigjoergensen** [comment]
I have stared for hours this morning and couldnt see the forest for all the trees - thanks.

**Comment by stigjoergensen** [comment]
Case closed
